---
- hosts: all
  remote_user: stack
  tasks:
  - name: copy jinja template
    template:
      src: vars/standalone_parameters.yaml.j2
      dest: "$HOME/standalone_parameters.yaml"

  - name: update the standalone_parameters
    shell:
      cmd: echo "NovaComputeLibvirtType: qemu" >> $HOME/standalone_parameters.yaml
      when: $NODE_TYPE == "vm"

  - name: Deploy the OSP environment
    shell: >
      sudo openstack tripleo deploy
      --templates
      --local-ip=$NODE_IP/$NETMASK
      -e /usr/share/openstack-tripleo-heat-templates/environments/standalone/standalone-tripleo.yaml
      -r /usr/share/openstack-tripleo-heat-templates/roles/Standalone.yaml
      -e $HOME/containers-prepare-parameters.yaml
      -e $HOME/standalone_parameters.yaml
      --output-dir $HOME
      --standalone

